### ISSUE TITLE
Haplotype assembly using strongly connected components-- How to interpret the haplotype assembly results and choose the best haplotype block?

### ISSUE THREAD

**Issue by nadiabaig** [smajidian/Hap10#1]
The strongly connected components  (e.g 10 files) yield 10 haplotype bock files.
Each hap file contains the same SNP position but with different order of haplotypes.
example:
**file1.hap**
`block1
Chr     SNPid   Position        Hap_0   Hap_1   Hap_2   Hap_3
Chr01   VAR_POS_6636    6636    G       G       G       A
Chr01   VAR_POS_6647    6647    T       T       T       G
Chr01   VAR_POS_6663    6663    T       T       T       C

block2
Chr     SNPid   Position        Hap_0   Hap_1   Hap_2   Hap_3
Chr01   VAR_POS_16739   16739   C       C       C       A
Chr01   VAR_POS_16781   16781   T       T       T       C
Chr01   VAR_POS_16804   16804   C       C       C       T
Chr01   VAR_POS_17051   17051   T       C       C       C`

**file2.hap**
` block1
Chr     SNPid   Position        Hap_0   Hap_1   Hap_2   Hap_3
Chr01   VAR_POS_6636    6636    G       G       G       A
Chr01   VAR_POS_6647    6647    T       T       T       G
Chr01   VAR_POS_6663    6663    T       T       T       C

block2
Chr     SNPid   Position        Hap_0   Hap_1   Hap_2   Hap_3
Chr01   VAR_POS_16739   16739   C       A       C       C
Chr01   VAR_POS_16781   16781   T       C       T       T
Chr01   VAR_POS_16804   16804   C       T       C       C
Chr01   VAR_POS_17051   17051   C       C       C       T`

**file3.hap**
`block1
Chr     SNPid   Position        Hap_0   Hap_1   Hap_2   Hap_3
Chr01   VAR_POS_6636    6636    G       G       G       A
Chr01   VAR_POS_6647    6647    T       T       T       G
Chr01   VAR_POS_6663    6663    T       T       T       C

block2
Chr     SNPid   Position        Hap_0   Hap_1   Hap_2   Hap_3
Chr01   VAR_POS_16739   16739   C       C       C       A
Chr01   VAR_POS_16781   16781   T       T       T       C
Chr01   VAR_POS_16804   16804   C       C       C       T
Chr01   VAR_POS_17051   17051   C       C       T       C`

My question is out of all these files which blocks are considered true for further processing. Each cluster file generates blocks with same positions but with the different order of alleles in haplotypes.

Secondly, I noticed that SNPs belonging to 1 block has no information of haplotypes, but same SNPs are reported in the second block but this time with the haplotype information. Why is this so? Example output is given.

**file1.hap**
` Block 1
Chr01   VAR_POS_17834   17834   G       A       G       G
Chr01   VAR_POS_17836   17836   G       A       A       G
Chr01   VAR_POS_18616   18616   -       -       -       -
Chr01   VAR_POS_18657   18657   -       -       -       -
Chr01   VAR_POS_18689   18689   -       -       -       -

Block2
Chr     SNPid   Position        Hap_0   Hap_1   Hap_2   Hap_3
Chr01   VAR_POS_18616   18616   T       C       C       T
Chr01   VAR_POS_18657   18657   G       A       A       G
Chr01   VAR_POS_18689   18689   G       T       T       T
Chr01   VAR_POS_18727   18727   A       G       G       G
Chr01   VAR_POS_18732   18732   T       A       A       A
Chr01   VAR_POS_18733   18733   A       C       C       C
`
So overall, the difference in haplotype information in each file plus SNPs with no haplotypes in block1 but with the haplotype information in second block is confusing me. How to proceed further with these haplotype files??

Looking forward for a nice explanation.
Plus it would be nice, if more details must be provided on the git-hub tutorial, explaining how to interpret the final haplotype assembly results.

Best wishes,
Nadia

**Comment by smajidian** [comment]
Hi Nadia

Thanks again for using our tool and sharing your feedbacks.

I normally expect to have different SNPs among haplotype blocks.  My guess is that the coverage (depth) is not enough, since haplotyping algorithms need at least a depth of 20. Another reason could be related to the number of SNPs. If this is too low, the spectral clustering of fragments doesn't work well. For a typical genome and using 10x genomics technology,  we expect hundreds of SNPs hundreds of fragments for each haplotype block.

So if you see many fragment files outJ_K.txt  that have only few rows (fragments),  I would suggest to use `cc` instead of `scc` in your case. 
```
python3  extract_scc.py fragment.txt cc ./out
```
If not solved, I could write a piece of code as the post-processing and iterate over haplotype blocks and store the SNPs. Then for the next blocks, the code removes the SNPs that exist in the previous block.

About '-' which I call them unphased SNPs, we can simply remove them. It is likely for each algorithm that is not able to phase some of the SNPs. This can root in lack of coverage, lack of enough support in the reads, or even avoiding computational burden since the haplotype assembly problem is a computationally NP-hard problem.

Hope that helps. 
Regards,
Sina

**Comment by nadiabaig** [comment]
Thanks for the detailed explanation.
I have one more question about binning/clustering data.
The mean_shift.py code throws user warning:

python3.8/site-packages/sklearn/cluster/_mean_shift.py:236: UserWarning: Binning data failed with provided bin_size=25000.000000, using data points as seeds.

What is the possible reason for this?

**Comment by smajidian** [comment]
You're welcome. 
The warning doesn't seem to be critical to me. It roots back in [here](https://github.com/scikit-learn/scikit-learn/blob/2beed55847ee70d363bdbfe14ee4401438fba057/sklearn/cluster/_mean_shift.py#L235) and the argument of splitter.py, molecule_length=50*1000, which is used as  bandwidth = molecule_length/2 =  bin_size. 
We have used the sklearn implementation of Mean shift clustering to find the boundaries of 10X molecule within each GEM bead based on the genomic position of mapped reads. 
We used `bin_seeding=True`.  The algorithm, in the first step, splits (grid) the genome to small region with the size of (predefined molecule length/2) and counts the number of mapped reads on that.
The seeds are the initial center (kernel )of each cluster. I guess since the number of molecule is limited and some part of genome are unknown (Ns) , we may not expect to have several of them in each. The warning says that all the input reads clustered into different molecule as the initial guess. As the mean shift clustering iterates to next step, it handles the issue itself. 

Regards,
Sina
